ktor:
    application:
        modules:
            - config.ktor.ApplicationKt.module
    deployment:
        port: 8080

    aws:
        s3:
            region: "eu-north-1"
            bucketName: "tasklearningbucket"
            accessKey: "$AWS_ACCESS_KEY_ID"
            secretKey: "$AWS_SECRET_ACCESS_KEY"
            urlExpirationSeconds: 3600

database:
    driverClassName: org.postgresql.Driver
    jdbcURL: "jdbc:postgresql://localhost:5432/ktor_todo_db"
    defaultJdbcURL: "jdbc:postgresql://localhost:5432/postgres"
    user: "ktor"
    password: "ktor"
    dbName: "ktor_todo_db"

flyway:
    url: "jdbc:postgresql://localhost:5432/ktor_todo_db"
    user: "ktor"
    password: "ktor"
    locations: "classpath:db/migrations"
    baselineOnMigrate: true

jwt:
    secret: "$JWT_SECRET"
    issuer: "ktor-exposed-task-app"
    audience: "ktor-audience"
    realm: "ktor-app"
    accessToken:
        lifetime: 3600000  # 1 hodina v milisekundách
    refreshToken:
        lifetime: 2592000000  # 30 dní v milisekundách

oauth:
    google:
        clientId: "$GOOGLE_OAUTH_CLIENT_ID"
        clientSecret: "$GOOGLE_OAUTH_CLIENT_SECRET"